name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the CIM Migration Project Repository. This will be the center for this project, please take a look around and get familiar!'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
